from .coil_agent import CoILAgent
from .eccv_generalization_suite import EccvGeneralization
from .eccv_training_suite import EccvTraining
from .test_t1_suite import TestT1
from .test_t2_suite import TestT2
from .pa_training_suite import PATraining
from .pa_new_weather_town_suite import PANewWeatherTown
from .pa_new_weather_suite import PANewWeather
from .pa_new_town_suite import PANewTown
from .pa_training_col_suite import PATrainingCol
from .pa_new_weather_town_col_suite import PANewWeatherTownCol
from .pa_new_weather_col_suite import PANewWeatherCol
from .pa_new_town_col_suite import PANewTownCol
